---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: dockerfile-creation
spec:
  params:
    - name: bundle_path
  workspaces:
    - name: source
  steps:
    - name: generate-dockerfile
      image: registry.access.redhat.com/ubi8-minimal
      workingDir: $(workspaces.source.path)
      script: |
        #! /usr/bin/env bash
        echo "This step will generate a bundle dockerfile"
