---
- name: Configure Namespace
  tags:
    - namespace
    - init
  kubernetes.core.k8s:
    state: "present"
    definition:
      kind: Namespace
      apiVersion: v1
      metadata:
        name: "{{ oc_namespace }}"

- name: Create service account
  tags:
    - service-account
    - init
  kubernetes.core.k8s:
    state: present
    namespace: "{{ oc_namespace }}"
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: "{{ service_account_name }}"
