---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: index-signature-verification-pipeline
spec:
  workspaces:
    - name: registry-credentials
  tasks:
    - name: verify-signatures-certified-operators
      timeout: "1h30m"
      taskRef:
        name: verify-index-signatures
      workspaces:
        - name: registry-credentials
          workspace: registry-credentials
      params:
        - name: organization
          value: certified-operators

    - name: verify-signatures-redhat-marketplace
      timeout: "1h30m"
      taskRef:
        name: verify-index-signatures
      workspaces:
        - name: registry-credentials
          workspace: registry-credentials
      params:
        - name: organization
          value: redhat-marketplace

    - name: verify-signatures-community-operators
      timeout: "1h30m"
      taskRef:
        name: verify-index-signatures
      workspaces:
        - name: registry-credentials
          workspace: registry-credentials
      params:
        - name: organization
          value: community-operators
