---
- name: Execute integration tests
  hosts: operator-pipeline-integration-tests-{{ test_type }}

  module_defaults:
    group/kubernetes.core.k8s:
      kubeconfig: "{{ lookup('env', 'HOME') }}/.kube/config"

  tasks:
    - name: Deploy environment and run tests
      block:
        - name: Deploy pipelines
          import_role:
            name: operator-pipeline
          tags:
            - pipeline
        - name: Run integration tests
          import_role:
            name: integration_tests
      always:
        - name: Cleanup operator pipeline
          import_role:
            name: operator-pipeline
            tasks_from: cleanup
