---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ operator_pipeline_webhook_dispatcher_cookie_secret_name }}"
  labels:
    app: "{{ operator_pipeline_webhook_dispatcher_name }}"
    suffix: "{{ suffix }}"
    env: "{{ env }}"
type: Opaque
stringData:
  cookie-secret: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"
