---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: certification-project-check
spec:
  params:
    - name: pipeline_image
    - name: affected_operators
      description: Comma separated list of affected operators
      default: ""
    - name: affected_catalog_operators
      description: Comma separated list of affected catalog operators
      default: ""
    - name: cert_project_required
      description: A flag determines whether a cert project ID needs to be present
      default: "true"
  results:
    - name: certification_project_id
      description: Identifier of certification project from Red Hat Connect
  workspaces:
    - name: source
    - name: base
      description: Clone of the repo at head of the base branch
      optional: true
  steps:
    - name: certification-project-check
      image: "$(params.pipeline_image)"
      workingDir: $(workspaces.source.path)
      script: |
        #! /usr/bin/env bash
        set -xe

        EXTRA_ARGS=""
        if [[ "$(workspaces.base.bound)" == "true" ]]; then
          EXTRA_ARGS+=" --repo-base-path $(workspaces.base.path)"
        fi

        certification-project-check \
          --repo-head-path "$(workspaces.source.path)" \
          --affected-operators "$(params.affected_operators)" \
          --affected-catalog-operators "$(params.affected_catalog_operators)" \
          --cert-project-required "$(params.cert_project_required)" \
          --output-file "$(results.certification_project_id.path)" \
          --verbose \
          $EXTRA_ARGS
