---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: dockerfile-creation
spec:
  params:
    - name: pipeline_image
    - name: bundle_path
  results:
    - name: bundle_dockerfile_path
  workspaces:
    - name: source
  steps:
    - name: generate-dockerfile
      image: "$(params.pipeline_image)"
      workingDir: $(workspaces.source.path)
      script: |
        #! /usr/bin/env bash
        set -xe

        if [ -z "$(params.bundle_path)" ]; then
          echo "No bundle added or changed"
          exit 0
        fi

        DOCKERFILE_PATH=Dockerfile

        bundle-dockerfile \
          --bundle-path $(params.bundle_path) \
          --destination $DOCKERFILE_PATH \
          --verbose

        cat $DOCKERFILE_PATH

        echo $DOCKERFILE_PATH | tee $(results.bundle_dockerfile_path.path)
